/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_Paquete;

import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class loginfi extends javax.swing.JFrame {

    int xmause, ymause;
    
    public loginfi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        city = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        HEAD = new javax.swing.JPanel();
        salidabtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Plataforma = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TITLE = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        passwordlabel = new javax.swing.JLabel();
        userlabel = new javax.swing.JLabel();
        PasswordField1 = new javax.swing.JPasswordField();
        BOTONINI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        city.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\login2\\src\\imagenes\\city.png")); // NOI18N
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 290, -1));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\login2\\src\\imagenes\\images.jpg")); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 220, 150));

        HEAD.setBackground(new java.awt.Color(255, 255, 255));
        HEAD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HEADMouseDragged(evt);
            }
        });
        HEAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HEADMousePressed(evt);
            }
        });

        salidabtn.setBackground(new java.awt.Color(255, 255, 255));
        salidabtn.setToolTipText("X");
        salidabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salidabtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salidabtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salidabtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salidabtnMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");

        javax.swing.GroupLayout salidabtnLayout = new javax.swing.GroupLayout(salidabtn);
        salidabtn.setLayout(salidabtnLayout);
        salidabtnLayout.setHorizontalGroup(
            salidabtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );
        salidabtnLayout.setVerticalGroup(
            salidabtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salidabtnLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout HEADLayout = new javax.swing.GroupLayout(HEAD);
        HEAD.setLayout(HEADLayout);
        HEADLayout.setHorizontalGroup(
            HEADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADLayout.createSequentialGroup()
                .addComponent(salidabtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 825, Short.MAX_VALUE))
        );
        HEADLayout.setVerticalGroup(
            HEADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADLayout.createSequentialGroup()
                .addComponent(salidabtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel1.add(HEAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        Plataforma.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        Plataforma.setText("PLATAFORMA PARA DOCENTE");
        jPanel1.add(Plataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 280, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\login2\\src\\imagenes\\193318.png")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 100));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 430, 190));

        TITLE.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        TITLE.setText("INICIAR SESIÓN");
        jPanel1.add(TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 320, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 320, 10));

        passwordlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordlabel.setText("CONTRASEÑA");
        jPanel1.add(passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 130, -1));

        userlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userlabel.setText("USUARIO");
        jPanel1.add(userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, -1));

        PasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        PasswordField1.setText("********");
        PasswordField1.setBorder(null);
        PasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordField1MousePressed(evt);
            }
        });
        PasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 320, 20));

        BOTONINI.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRAR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout BOTONINILayout = new javax.swing.GroupLayout(BOTONINI);
        BOTONINI.setLayout(BOTONINILayout);
        BOTONINILayout.setHorizontalGroup(
            BOTONINILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOTONINILayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BOTONINILayout.setVerticalGroup(
            BOTONINILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BOTONINILayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(BOTONINI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 130, 40));

        usertxt.setForeground(new java.awt.Color(204, 204, 204));
        usertxt.setText("INGRESE SU USUARIO");
        usertxt.setBorder(null);
        usertxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usertxtMousePressed(evt);
            }
        });
        jPanel1.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 320, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField1ActionPerformed

    private void HEADMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEADMousePressed
        xmause=evt.getX();
        ymause=evt.getY();
    }//GEN-LAST:event_HEADMousePressed

    private void HEADMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEADMouseDragged
      int x= evt.getXOnScreen();
      int y=evt.getYOnScreen();
        
        this.setLocation(x-xmause,y- ymause);
    }//GEN-LAST:event_HEADMouseDragged

    private void salidabtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidabtnMouseEntered
salidabtn.setBackground(Color.red);
jLabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_salidabtnMouseEntered

    private void salidabtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidabtnMouseExited
salidabtn.setBackground(Color.white);
jLabel3.setForeground(Color.black);// TODO add your handling code here:
    }//GEN-LAST:event_salidabtnMouseExited

    private void salidabtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidabtnMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_salidabtnMouseClicked

    private void PasswordField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordField1MousePressed
   if (String.valueOf(PasswordField1.getPassword()).equals("********")){
PasswordField1.setText("");
PasswordField1.setForeground(Color.black);}
if(usertxt.getText().isEmpty()){
usertxt.setText("INGRESE SU USUARIO");
        usertxt.setForeground(Color.gray);}
    }//GEN-LAST:event_PasswordField1MousePressed

    private void usertxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertxtMousePressed
      if(usertxt.getText().equals("INGRESE SU USUARIO")){
        usertxt.setText("");
        usertxt.setForeground(Color.black);}
if (String.valueOf(PasswordField1.getPassword()).isEmpty()){
        PasswordField1.setText("********");
PasswordField1.setForeground(Color.gray);}
    }//GEN-LAST:event_usertxtMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginfi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginfi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginfi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginfi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginfi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BOTONINI;
    private javax.swing.JPanel HEAD;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JLabel Plataforma;
    private javax.swing.JLabel TITLE;
    private javax.swing.JLabel city;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JPanel salidabtn;
    private javax.swing.JLabel userlabel;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
